#login information
login_info:
    baseURL: 'https://admin-demo.nopcommerce.com/'
    username: 'admin@yourstore.com'
    password: 'admin'

path:
  python_path: '/Users/kelly/PycharmProjects/framework_template/'
